<?php

/**
 * File: app/Http/Controllers/AttachmentController.php
 * Responsibility: Streams one attachment to a signed-in, authorized user.
 * What it does:
 * - Applies Attachment::canBeViewedBy() before anything is read from disk, so
 *   a guessed URL cannot reach another company's or an internal-only file.
 * - Streams the file from its own disk — images inline, everything else as a
 *   download — with nosniff and a short private cache.
 * - `?size=thumb|medium|large` serves a resized WebP for resizable images
 *   (cached per file version); anything else falls back to the original file.
 * How to use: GET route `attachments.show`, generated by Attachment::url.
 * How to extend: add another size to SIZES; the route and fallbacks follow.
 */

namespace App\Http\Controllers;

use App\Models\Attachment;
use App\Models\User;
use Awcodes\Curator\Facades\Curator;
use Awcodes\Curator\Facades\Glide;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Interfaces\ImageInterface;
use Symfony\Component\HttpFoundation\Response;
use Throwable;

class AttachmentController extends Controller
{
    /**
     * The raster types that may render in place; anything else downloads, so
     * stored bytes can never talk the browser into rendering a document (or
     * markup) as a page on the app's origin.
     *
     * @var list<string>
     */
    private const INLINE_TYPES = [
        'image/jpeg',
        'image/png',
        'image/gif',
        'image/webp',
        'image/avif',
        'image/bmp',
    ];

    /**
     * Requested size => [width, height, mode]; `cover` crops to fill the box
     * (downscaling only), `contain` fits inside it without upscaling.
     *
     * @var array<string, array{int, int, string}>
     */
    private const SIZES = [
        'thumb' => [200, 200, 'cover'],
        'medium' => [640, 640, 'cover'],
        'large' => [1024, 1024, 'contain'],
    ];

    public function __invoke(Request $request, Attachment $attachment): Response
    {
        $user = $request->user();

        abort_unless($user instanceof User && $attachment->canBeViewedBy($user), 403);
        abort_unless(filled($attachment->path) && Storage::disk($attachment->disk)->exists($attachment->path), 404);

        if (($thumbnail = $this->thumbnailResponse($request, $attachment)) !== null) {
            return $thumbnail;
        }

        return Storage::disk($attachment->disk)->response($attachment->path, headers: [
            'X-Content-Type-Options' => 'nosniff',
            'Cache-Control' => 'private, max-age=300',
        ], disposition: in_array($attachment->type, self::INLINE_TYPES, true) ? 'inline' : 'attachment');
    }

    /**
     * The resized WebP for the requested size, or null when no (or an
     * unknown) size was asked for, the file is not a resizable image, or the
     * resize failed — in all of those cases the original file is served.
     * Bytes are cached per attachment, size and file version.
     */
    private function thumbnailResponse(Request $request, Attachment $attachment): ?Response
    {
        $bounds = self::SIZES[(string) $request->query('size', '')] ?? null;

        if ($bounds === null || ! Curator::isResizable((string) $attachment->ext)) {
            return null;
        }

        [$width, $height, $mode] = $bounds;
        $disk = Storage::disk($attachment->disk);
        $version = (string) $disk->lastModified($attachment->path);

        $bytes = Cache::remember(
            "attachment-{$attachment->getKey()}-{$bounds[0]}x{$bounds[1]}-{$version}",
            now()->addDay(),
            function () use ($disk, $attachment, $width, $height, $mode): ?string {
                try {
                    $image = Glide::getServer()->getApi()->getImageManager()->read($disk->get($attachment->path));

                    return $this->fitToBox($image, $width, $height, $mode)->toWebp(80)->toString();
                } catch (Throwable) {
                    return null;
                }
            },
        );

        if (! is_string($bytes)) {
            return null;
        }

        return response($bytes, 200, [
            'Content-Type' => 'image/webp',
            'Content-Length' => (string) strlen($bytes),
            'X-Content-Type-Options' => 'nosniff',
            'Cache-Control' => 'private, max-age=86400',
        ]);
    }

    /**
     * `cover` fills the box and crops, but only shrinks; `contain` fits the
     * box and never upscales either, so a small photo is served as it is.
     */
    private function fitToBox(ImageInterface $image, int $width, int $height, string $mode): ImageInterface
    {
        if ($mode === 'contain') {
            return $image->scaleDown($width, $height);
        }

        return $image->size()->width() <= $width && $image->size()->height() <= $height
            ? $image
            : $image->cover($width, $height);
    }
}
